/// IRS mileage rates and tax constants.
/// Update yearly when IRS announces new rates.
class IrsRates {
  IrsRates._();

  /// 2026 Standard Mileage Rate (cents per mile).
  /// Source: IRS Rev. Proc. 2025-13 (or successor). Edit as needed.
  static const double standardRate2026 = 0.72; // $0.72 per mile

  /// Current active rate used by the app (editable in settings).
  static double get currentRate => standardRate2026;

  /// Returns the deduction amount for given business miles.
  static double deductionForMiles(double miles, [double? customRate]) {
    final rate = customRate ?? currentRate;
    return miles * rate;
  }

  /// Formatted rate string e.g. "$0.72"
  static String get formattedRate => '\$${currentRate.toStringAsFixed(2)}';

  /// Strong legal disclaimer shown in PDFs and throughout the app.
  /// This is critical because the app produces documents people may use for taxes.
  static const String irsDisclaimer =
      'DISCLAIMER: This report was generated by MileMaid using GPS and motion data from your device. '
      'MileMaid is a tool to assist with record-keeping only. It is NOT tax advice, legal advice, or a substitute for a qualified tax professional or CPA. '
      'The IRS generally requires contemporaneous and accurate records. You are solely responsible for the accuracy of the information in this report and for any tax positions you take. '
      'MileMaid and its developers accept no liability for any tax assessments, penalties, audits, or other consequences arising from the use of this app or its generated documents. '
      'Consult your accountant or tax advisor before relying on any data or reports produced by MileMaid. '
      'Standard mileage rates are subject to change; verify the current IRS rate for your tax year.';

  static const String shortDisclaimer =
      'MileMaid is a record-keeping tool only and is not tax or legal advice. '
      'You are responsible for the accuracy of your records. Consult a qualified tax professional.';
}
